SELECT * FROM openiddictentityframeworkcorescope;
SELECT * FROM openiddictentityframeworkcoretoken;
SELECT * FROM openiddictentityframeworkcoreauthorization;
SELECT * FROM openiddictentityframeworkcoreapplication;

TRUNCATE openiddictentityframeworkcoretoken;
TRUNCATE openiddictentityframeworkcorescope;
TRUNCATE openiddictentityframeworkcoreauthorization;
TRUNCATE openiddictentityframeworkcoreapplication;



